### ISSUE TITLE
Auth Setup

### ISSUE THREAD

**Issue by navn-r** [navn-r/drawhub#7]
**TODO**:

- [x] Create auth0 tenant with google sign-in only

- [x] Integrate with Server (`/auth`)

- [x] Connect with Client (Get Started Button)
